Fix Gradle error due to runtest.sh
Error: Exception in thread "main" java.util.NoSuchElementException: No line found
 at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
 at seedu.lifetrack.LifeTrack.main(LifeTrack.java:22)
./runtest.sh: line 14: dos2unix: command not found